name: registro_argo
description: Flutter client for argo school record.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # api client
  dio: ^3.0.8
  # Functional programming
  dartz: ^0.8.9
  # object comparison
  equatable: ^1.0.2
  # check connection
  data_connection_checker: ^0.3.4
  # dependency injection
  get_it: ^3.1.0
  # bloc state managament
  flutter_bloc: ^3.1.0
  # database
  moor_flutter:
  # logging
  f_logs: ^1.2.2
  # save user password
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.4+8
  # in18n
  intl: ^0.16.0
  flutter_svg: ^0.15.0

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  build_runner:

flutter:
  assets:
    - assets/images/green_waves.svg
    - lang/en.json
    - lang/it.json
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.otf
          style: italic
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 200
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 300
